### ISSUE TITLE
BO/SM  9pt and 13pt skill on mid path

### ISSUE THREAD

**Issue by Tesq** [mattyrichards/ror-career-builder#1]
on ror they have been swapped to balance SM/BO if you follow ror implementation you need to swap those skills in their position.

exemple: both KD should be on 9 pt instead 13 and 9pt skill should be moved to 13

**Comment by mttrchrds** [comment]
Thanks for the bug report mate. This should be fixed now. Can you have a check and confirm?

**Comment by mttrchrds** [comment]
Looks fixed to me. Thanks for pointing it out.
