### ISSUE TITLE
Update for patches

### ISSUE THREAD

**Issue by Ramasee** [mattyrichards/ror-career-builder#14]
There have been a number of patches recently that have made the data input into the ror career builder obsolete. 

I don't know if you play much anymore, but it would appreciated if it could be updated.

Also, I am willing to put in the text changes if you are willing to show me how. I went looking for it in the code provided here and only found references but no inputs.

**Comment by XmatXergon** [comment]
If u change branch to Redux, then go to folder Public and there you will find Abilities for all classes.
I cloned this repository and trying to understand how it works, its quiet simply, but even if you update it yourself, someone has to push it on live/online.
They told me to contact Dansari, so i suggest you to do same if u want to help.

**Comment by Ramasee** [comment]
Lol, I searched through all that code when I had downloaded it. Yet I downloaded the public one, which doesn't have the abilities. Thanks for pointing out the branch to me, I never used github. Yeah I'll poke dan, although nath said they were having a propagation issue; so we'll see.

**Comment by mttrchrds** [comment]
> Lol, I searched through all that code when I had downloaded it. Yet I downloaded the public one, which doesn't have the abilities. Thanks for pointing out the branch to me, I never used github. Yeah I'll poke dan, although nath said they were having a propagation issue; so we'll see.

Hey @Ramasee, apologies for not replying sooner. I've been chatting with Nath and I'm aware that you've got a fork up and running with Nath hosting the abilities JSON files. This sounds great.

Please get in touch via the RoR forums to exchange email addresses. I'll be happy to help with any issues you may have when making updates. My profile is here: https://www.returnofreckoning.com/forum/memberlist.php?mode=viewprofile&u=70322
