### ISSUE TITLE
[chosen] discordant fluctuation icon

### ISSUE THREAD

**Issue by Tesq** [mattyrichards/ror-career-builder#2]
replace with this one here
![abi_ch_violetfire](https://cloud.githubusercontent.com/assets/7527415/15727950/dcf30e12-2859-11e6-939d-4a68818c3676.png)

**Comment by mttrchrds** [comment]
Many thanks. I've updated on live.

**Comment by Tesq** [comment]
your change also changed the quake icon, they should be different the previously one was right for quake and wrong for the discordiant fluctuation

**Comment by mttrchrds** [comment]
Didn't realise they were using the same icon :(

Anyway, should hopefully be fixed now.
